# Source Generated with Decompyle++
# File: os_platform.pyc (Python 3.10)

'''
    User-Facing Feature Flag API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
'''
from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self

class OSPlatform(Enum, str):
    '''
    OSPlatform
    '''
    WINDOWS = 'windows'
    MACOS = 'macos'
    LINUX = 'linux'
    OTHER = 'other'
    
    def from_json(cls = None, json_str = None):
        '''Create an instance of OSPlatform from a JSON string'''
        return cls(json.loads(json_str))

    from_json = None(from_json)

