# Source Generated with Decompyle++
# File: ui_flasher_form.pyc (Python 3.10)

from PySide6.QtCore import QCoreApplication, QDate, QDateTime, QLocale, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt
from PySide6.QtGui import QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QGradient, QIcon, QImage, QKeySequence, QLinearGradient, QPainter, QPalette, QPixmap, QRadialGradient, QTransform
from PySide6.QtWidgets import QApplication, QLabel, QPushButton, QSizePolicy, QWidget
from  import resources_rc

class Ui_FlasherForm(object):
    
    def setupUi(self, FlasherForm):
        if not FlasherForm.objectName():
            FlasherForm.setObjectName('FlasherForm')
        FlasherForm.resize(625, 432)
        font = QFont()
        font.setPointSize(9)
        FlasherForm.setFont(font)
        FlasherForm.setAutoFillBackground(False)
        FlasherForm.setStyleSheet('color: rgb(255, 255, 255);\nbackground: transparent')
        self.close_btn = QPushButton(FlasherForm)
        self.close_btn.setObjectName('close_btn')
        self.close_btn.setGeometry(QRect(585, 18, 24, 23))
        self.close_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.close_btn.setStyleSheet('')
        icon = QIcon()
        icon.addFile(':/images/images/x_btn.png', QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QSize(24, 23))
        self.dragger = QLabel(FlasherForm)
        self.dragger.setObjectName('dragger')
        self.dragger.setGeometry(QRect(30, 46, 560, 49))
        self.dragger.setCursor(QCursor(Qt.CursorShape.OpenHandCursor))
        self.dragger.setStyleSheet('')
        self.btn_tab_system = QPushButton(FlasherForm)
        self.btn_tab_system.setObjectName('btn_tab_system')
        self.btn_tab_system.setGeometry(QRect(40, 15, 35, 30))
        self.btn_tab_system.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_tab_system.setStyleSheet('background: transparent;')
        self.btn_tab_cartclinic = QPushButton(FlasherForm)
        self.btn_tab_cartclinic.setObjectName('btn_tab_cartclinic')
        self.btn_tab_cartclinic.setGeometry(QRect(86, 15, 35, 30))
        self.btn_tab_cartclinic.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_tab_cartclinic.setStyleSheet('background: transparent;')
        self.tab_system = QWidget(FlasherForm)
        self.tab_system.setObjectName('tab_system')
        self.tab_system.setGeometry(QRect(0, 0, 625, 432))
        self.tab_about = QWidget(FlasherForm)
        self.tab_about.setObjectName('tab_about')
        self.tab_about.setGeometry(QRect(0, 0, 625, 432))
        self.tab_manufacturing = QWidget(FlasherForm)
        self.tab_manufacturing.setObjectName('tab_manufacturing')
        self.tab_manufacturing.setGeometry(QRect(0, 0, 625, 432))
        self.btn_tab_manufacturing = QPushButton(FlasherForm)
        self.btn_tab_manufacturing.setObjectName('btn_tab_manufacturing')
        self.btn_tab_manufacturing.setGeometry(QRect(515, 12, 42, 38))
        self.btn_tab_manufacturing.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_tab_manufacturing.setStyleSheet('background: transparent;')
        icon1 = QIcon()
        icon1.addFile(':/fonts/images/tab4_btn.png', QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_tab_manufacturing.setIcon(icon1)
        self.btn_tab_manufacturing.setIconSize(QSize(42, 38))
        self.btn_tab_about = QPushButton(FlasherForm)
        self.btn_tab_about.setObjectName('btn_tab_about')
        self.btn_tab_about.setGeometry(QRect(131, 15, 35, 30))
        self.btn_tab_about.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_tab_about.setStyleSheet('background: transparent;')
        self.tab_cartclinic = QWidget(FlasherForm)
        self.tab_cartclinic.setObjectName('tab_cartclinic')
        self.tab_cartclinic.setGeometry(QRect(0, 0, 625, 432))
        self.chromatic_manual_link = QPushButton(FlasherForm)
        self.chromatic_manual_link.setObjectName('chromatic_manual_link')
        self.chromatic_manual_link.setGeometry(QRect(35, 381, 100, 22))
        self.chromatic_manual_link.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chromatic_manual_link.setStyleSheet('')
        icon2 = QIcon()
        icon2.addFile(':/images/images/manual_link.png', QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.chromatic_manual_link.setIcon(icon2)
        self.chromatic_manual_link.setIconSize(QSize(100, 22))
        self.bg = QLabel(FlasherForm)
        self.bg.setObjectName('bg')
        self.bg.setGeometry(QRect(0, 0, 625, 432))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg.sizePolicy().hasHeightForWidth())
        self.bg.setSizePolicy(sizePolicy)
        self.bg.setPixmap(QPixmap(':/images/images/bg.png'))
        self.bg.setScaledContents(True)
        self.splash = QLabel(FlasherForm)
        self.splash.setObjectName('splash')
        self.splash.setGeometry(QRect(0, 0, 625, 432))
        self.splash.setPixmap(QPixmap(':/images/images/title.png'))
        self.splash.setScaledContents(True)
        self.splash.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bg.raise_()
        self.splash.raise_()
        self.btn_tab_about.raise_()
        self.btn_tab_cartclinic.raise_()
        self.dragger.raise_()
        self.close_btn.raise_()
        self.btn_tab_system.raise_()
        self.tab_about.raise_()
        self.tab_manufacturing.raise_()
        self.btn_tab_manufacturing.raise_()
        self.chromatic_manual_link.raise_()
        self.tab_cartclinic.raise_()
        self.tab_system.raise_()
        self.retranslateUi(FlasherForm)
        QMetaObject.connectSlotsByName(FlasherForm)

    
    def retranslateUi(self, FlasherForm):
        FlasherForm.setWindowTitle(QCoreApplication.translate('FlasherForm', 'GUI', None))
        self.close_btn.setText('')
        self.dragger.setText('')
        self.btn_tab_system.setToolTip(QCoreApplication.translate('FlasherForm', 'System Update', None))
        self.btn_tab_system.setText('')
        self.btn_tab_cartclinic.setToolTip(QCoreApplication.translate('FlasherForm', 'Cart Clinic', None))
        self.btn_tab_cartclinic.setText('')
        self.btn_tab_manufacturing.setText('')
        self.btn_tab_about.setToolTip(QCoreApplication.translate('FlasherForm', 'About', None))
        self.btn_tab_about.setText('')
        self.chromatic_manual_link.setText('')
        self.bg.setText('')
        self.splash.setText('')


